services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: reema213
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DB_HOST=db
    command: ["sh", "-c", "sleep 15 && java -jar app.jar"]
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data: